name: gplx
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  vibration: ^1.9.0
  go_router: ^14.2.3
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  path: ^1.9.0
  csv: ^6.0.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/questions.csv
    - assets/data/signs.csv

    - assets/images/home-image.jpg
    - assets/images/avatar.jpg
    - assets/images/place-holder.png
    - assets/images/placeholder-icon.png

    - assets/data/images_of_question/72.png
    - assets/data/images_of_question/73.png
    - assets/data/images_of_question/74.png
    - assets/data/images_of_question/75.png
    - assets/data/images_of_question/82.png
    - assets/data/images_of_question/83.png
    - assets/data/images_of_question/188.png
    - assets/data/images_of_question/189.png
    - assets/data/images_of_question/190.png
    - assets/data/images_of_question/191.png
    - assets/data/images_of_question/192.png
    - assets/data/images_of_question/235.png
    - assets/data/images_of_question/236.png
    - assets/data/images_of_question/237.png
    - assets/data/images_of_question/238.png
    - assets/data/images_of_question/239.png
    - assets/data/images_of_question/292.png
    - assets/data/images_of_question/293.png
    - assets/data/images_of_question/294.png
    - assets/data/images_of_question/295.png
    - assets/data/images_of_question/296.png
    - assets/data/images_of_question/301.png
    - assets/data/images_of_question/302.png
    - assets/data/images_of_question/303.png
    - assets/data/images_of_question/304.png
    - assets/data/images_of_question/305.png
    - assets/data/images_of_question/306.png
    - assets/data/images_of_question/307.png
    - assets/data/images_of_question/308.png
    - assets/data/images_of_question/309.png
    - assets/data/images_of_question/310.png
    - assets/data/images_of_question/311.png
    - assets/data/images_of_question/312.png
    - assets/data/images_of_question/313.png
    - assets/data/images_of_question/314.png
    - assets/data/images_of_question/315.png
    - assets/data/images_of_question/316.png
    - assets/data/images_of_question/317.png
    - assets/data/images_of_question/318.png
    - assets/data/images_of_question/319.png
    - assets/data/images_of_question/320.png
    - assets/data/images_of_question/321.png
    - assets/data/images_of_question/322.png
    - assets/data/images_of_question/323.png
    - assets/data/images_of_question/324.png
    - assets/data/images_of_question/325.png
    - assets/data/images_of_question/326.png
    - assets/data/images_of_question/327.png
    - assets/data/images_of_question/328.png
    - assets/data/images_of_question/329.png
    - assets/data/images_of_question/330.png
    - assets/data/images_of_question/331.png
    - assets/data/images_of_question/332.png
    - assets/data/images_of_question/333.png
    - assets/data/images_of_question/334.png
    - assets/data/images_of_question/335.png
    - assets/data/images_of_question/336.png
    - assets/data/images_of_question/337.png
    - assets/data/images_of_question/338.png
    - assets/data/images_of_question/339.png
    - assets/data/images_of_question/340.png
    - assets/data/images_of_question/341.png
    - assets/data/images_of_question/342.png
    - assets/data/images_of_question/343.png
    - assets/data/images_of_question/344.png
    - assets/data/images_of_question/345.png
    - assets/data/images_of_question/346.png
    - assets/data/images_of_question/347.png
    - assets/data/images_of_question/348.png
    - assets/data/images_of_question/349.png
    - assets/data/images_of_question/350.png
    - assets/data/images_of_question/351.png
    - assets/data/images_of_question/352.png
    - assets/data/images_of_question/353.png
    - assets/data/images_of_question/354.png
    - assets/data/images_of_question/355.png
    - assets/data/images_of_question/356.png
    - assets/data/images_of_question/357.png
    - assets/data/images_of_question/358.png
    - assets/data/images_of_question/359.png
    - assets/data/images_of_question/360.png
    - assets/data/images_of_question/361.png
    - assets/data/images_of_question/362.png
    - assets/data/images_of_question/363.png
    - assets/data/images_of_question/364.png
    - assets/data/images_of_question/365.png
    - assets/data/images_of_question/366.png
    - assets/data/images_of_question/367.png
    - assets/data/images_of_question/368.png
    - assets/data/images_of_question/369.png
    - assets/data/images_of_question/370.png
    - assets/data/images_of_question/371.png
    - assets/data/images_of_question/372.png
    - assets/data/images_of_question/373.png
    - assets/data/images_of_question/374.png
    - assets/data/images_of_question/375.png
    - assets/data/images_of_question/376.png
    - assets/data/images_of_question/377.png
    - assets/data/images_of_question/378.png
    - assets/data/images_of_question/379.png
    - assets/data/images_of_question/380.png
    - assets/data/images_of_question/381.png
    - assets/data/images_of_question/382.png
    - assets/data/images_of_question/383.png
    - assets/data/images_of_question/384.png
    - assets/data/images_of_question/385.png
    - assets/data/images_of_question/386.png
    - assets/data/images_of_question/387.png
    - assets/data/images_of_question/388.png
    - assets/data/images_of_question/389.png
    - assets/data/images_of_question/390.png
    - assets/data/images_of_question/391.png
    - assets/data/images_of_question/392.png
    - assets/data/images_of_question/393.png
    - assets/data/images_of_question/394.png
    - assets/data/images_of_question/395.png
    - assets/data/images_of_question/396.png
    - assets/data/images_of_question/397.png
    - assets/data/images_of_question/398.png
    - assets/data/images_of_question/399.png
    - assets/data/images_of_question/400.png
    - assets/data/images_of_question/401.png
    - assets/data/images_of_question/402.png
    - assets/data/images_of_question/403.png
    - assets/data/images_of_question/404.png
    - assets/data/images_of_question/405.png
    - assets/data/images_of_question/406.png
    - assets/data/images_of_question/407.png
    - assets/data/images_of_question/408.png
    - assets/data/images_of_question/409.png
    - assets/data/images_of_question/410.png
    - assets/data/images_of_question/411.png
    - assets/data/images_of_question/412.png
    - assets/data/images_of_question/413.png
    - assets/data/images_of_question/414.png
    - assets/data/images_of_question/415.png
    - assets/data/images_of_question/416.png
    - assets/data/images_of_question/417.png
    - assets/data/images_of_question/418.png
    - assets/data/images_of_question/419.png
    - assets/data/images_of_question/420.png
    - assets/data/images_of_question/421.png
    - assets/data/images_of_question/422.png
    - assets/data/images_of_question/423.png
    - assets/data/images_of_question/424.png
    - assets/data/images_of_question/425.png
    - assets/data/images_of_question/426.png
    - assets/data/images_of_question/427.png
    - assets/data/images_of_question/428.png
    - assets/data/images_of_question/429.png
    - assets/data/images_of_question/430.png
    - assets/data/images_of_question/431.png
    - assets/data/images_of_question/432.png
    - assets/data/images_of_question/433.png
    - assets/data/images_of_question/434.png
    - assets/data/images_of_question/435.png
    - assets/data/images_of_question/436.png
    - assets/data/images_of_question/437.png
    - assets/data/images_of_question/438.png
    - assets/data/images_of_question/439.png
    - assets/data/images_of_question/440.png
    - assets/data/images_of_question/441.png
    - assets/data/images_of_question/442.png
    - assets/data/images_of_question/443.png
    - assets/data/images_of_question/444.png
    - assets/data/images_of_question/445.png
    - assets/data/images_of_question/446.png
    - assets/data/images_of_question/447.png
    - assets/data/images_of_question/448.png
    - assets/data/images_of_question/449.png
    - assets/data/images_of_question/450.png
    - assets/data/images_of_question/451.png
    - assets/data/images_of_question/452.png
    - assets/data/images_of_question/453.png
    - assets/data/images_of_question/454.png
    - assets/data/images_of_question/455.png
    - assets/data/images_of_question/456.png
    - assets/data/images_of_question/457.png
    - assets/data/images_of_question/458.png
    - assets/data/images_of_question/459.png
    - assets/data/images_of_question/460.png
    - assets/data/images_of_question/461.png
    - assets/data/images_of_question/462.png
    - assets/data/images_of_question/463.png
    - assets/data/images_of_question/464.png
    - assets/data/images_of_question/465.png
    - assets/data/images_of_question/466.png
    - assets/data/images_of_question/467.png
    - assets/data/images_of_question/468.png
    - assets/data/images_of_question/469.png
    - assets/data/images_of_question/470.png
    - assets/data/images_of_question/471.png
    - assets/data/images_of_question/472.png
    - assets/data/images_of_question/473.png
    - assets/data/images_of_question/474.png
    - assets/data/images_of_question/475.png
    - assets/data/images_of_question/476.png
    - assets/data/images_of_question/477.png
    - assets/data/images_of_question/478.png
    - assets/data/images_of_question/479.png
    - assets/data/images_of_question/480.png
    - assets/data/images_of_question/481.png
    - assets/data/images_of_question/482.png
    - assets/data/images_of_question/483.png
    - assets/data/images_of_question/484.png
    - assets/data/images_of_question/485.png
    - assets/data/images_of_question/486.png
    - assets/data/images_of_question/487.png
    - assets/data/images_of_question/488.png
    - assets/data/images_of_question/489.png
    - assets/data/images_of_question/490.png
    - assets/data/images_of_question/491.png
    - assets/data/images_of_question/492.png
    - assets/data/images_of_question/493.png
    - assets/data/images_of_question/494.png
    - assets/data/images_of_question/495.png
    - assets/data/images_of_question/496.png
    - assets/data/images_of_question/497.png
    - assets/data/images_of_question/498.png
    - assets/data/images_of_question/499.png
    - assets/data/images_of_question/500.png
    - assets/data/images_of_question/501.png
    - assets/data/images_of_question/502.png
    - assets/data/images_of_question/503.png
    - assets/data/images_of_question/504.png
    - assets/data/images_of_question/505.png
    - assets/data/images_of_question/506.png
    - assets/data/images_of_question/507.png
    - assets/data/images_of_question/508.png
    - assets/data/images_of_question/509.png
    - assets/data/images_of_question/510.png
    - assets/data/images_of_question/511.png
    - assets/data/images_of_question/512.png
    - assets/data/images_of_question/513.png
    - assets/data/images_of_question/514.png
    - assets/data/images_of_question/515.png
    - assets/data/images_of_question/516.png
    - assets/data/images_of_question/517.png
    - assets/data/images_of_question/518.png
    - assets/data/images_of_question/519.png
    - assets/data/images_of_question/520.png
    - assets/data/images_of_question/521.png
    - assets/data/images_of_question/522.png
    - assets/data/images_of_question/523.png
    - assets/data/images_of_question/524.png
    - assets/data/images_of_question/525.png
    - assets/data/images_of_question/526.png
    - assets/data/images_of_question/527.png
    - assets/data/images_of_question/528.png
    - assets/data/images_of_question/529.png
    - assets/data/images_of_question/530.png
    - assets/data/images_of_question/531.png
    - assets/data/images_of_question/532.png
    - assets/data/images_of_question/533.png
    - assets/data/images_of_question/534.png
    - assets/data/images_of_question/535.png
    - assets/data/images_of_question/536.png
    - assets/data/images_of_question/537.png
    - assets/data/images_of_question/538.png
    - assets/data/images_of_question/539.png
    - assets/data/images_of_question/540.png
    - assets/data/images_of_question/541.png
    - assets/data/images_of_question/542.png
    - assets/data/images_of_question/543.png
    - assets/data/images_of_question/544.png
    - assets/data/images_of_question/545.png
    - assets/data/images_of_question/546.png
    - assets/data/images_of_question/547.png
    - assets/data/images_of_question/548.png
    - assets/data/images_of_question/549.png
    - assets/data/images_of_question/550.png
    - assets/data/images_of_question/551.png
    - assets/data/images_of_question/552.png
    - assets/data/images_of_question/553.png
    - assets/data/images_of_question/554.png
    - assets/data/images_of_question/555.png
    - assets/data/images_of_question/556.png
    - assets/data/images_of_question/557.png
    - assets/data/images_of_question/558.png
    - assets/data/images_of_question/559.png
    - assets/data/images_of_question/560.png
    - assets/data/images_of_question/561.png
    - assets/data/images_of_question/562.png
    - assets/data/images_of_question/563.png
    - assets/data/images_of_question/564.png
    - assets/data/images_of_question/565.png
    - assets/data/images_of_question/566.png
    - assets/data/images_of_question/567.png
    - assets/data/images_of_question/568.png
    - assets/data/images_of_question/569.png
    - assets/data/images_of_question/570.png
    - assets/data/images_of_question/571.png
    - assets/data/images_of_question/572.png
    - assets/data/images_of_question/573.png
    - assets/data/images_of_question/574.png
    - assets/data/images_of_question/575.png
    - assets/data/images_of_question/576.png
    - assets/data/images_of_question/577.png
    - assets/data/images_of_question/578.png
    - assets/data/images_of_question/579.png
    - assets/data/images_of_question/580.png
    - assets/data/images_of_question/581.png
    - assets/data/images_of_question/582.png
    - assets/data/images_of_question/583.png
    - assets/data/images_of_question/584.png
    - assets/data/images_of_question/585.png
    - assets/data/images_of_question/586.png
    - assets/data/images_of_question/587.png
    - assets/data/images_of_question/588.png
    - assets/data/images_of_question/589.png
    - assets/data/images_of_question/590.png
    - assets/data/images_of_question/591.png
    - assets/data/images_of_question/592.png
    - assets/data/images_of_question/593.png
    - assets/data/images_of_question/594.png
    - assets/data/images_of_question/595.png
    - assets/data/images_of_question/596.png
    - assets/data/images_of_question/597.png
    - assets/data/images_of_question/598.png
    - assets/data/images_of_question/599.png
    - assets/data/images_of_question/600.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
